config/routes.rb
Rails.application.routes.draw do

  get 'about/index'
  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create', as: 'login/create'
  get '/register', to: 'users#new', as: 'register'
  post '/login', to: 'users#create', as: 'register/create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
  end

  get '/about', to: 'about#index', as: 'about'

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_admin!

  def show
    @product_count = Product.count
    @category_count = Category.count
  end

  private

  def authenticate_admin!
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['ADMIN_USERNAME'] && password == ENV['ADMIN_PASSWORD']
    end
  end

end

app/views/admin/dashboard/show.html.erb
<div class="container">
  <h1>Admin Dashboard</h1>

  <div class="row">
    <div class="col-md-6">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title">Total Products</h5>
          <p class="card-text"><%= @product_count %></p>
          <%= link_to admin_products_path, class: 'btn btn-primary' do %>
            View Products
          <% end %>
        </div>
      </div>
    </div>
    
    <div class="col-md-6">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title">Total Categories</h5>
          <p class="card-text"><%= @category_count %></p>
          <%= link_to admin_categories_path, class: 'btn btn-primary' do %>
            View Categories
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>